### PR TITLE
Added information about new experimental Xcode concurrent swift build…

### PR DESCRIPTION
**Pull request by quellish**
…s feature

### CODE REVIEW

**Comment by DenTelezhkin** [comment]
Does this feature even work? Build fails silently when i turn this on. All other improvements from this repo are turned on including new build system.

**Comment by quellish** [comment]
It does. Make sure you are using 9.2 release, not beta.

**Comment by DenTelezhkin** [comment]
Also this thread from Twitter:
https://twitter.com/rballard/status/938216933303885824

Seems like this flag was documented incorrectly and it does affect only old build system, not the new one.

**Comment by quellish** [comment]
That's what I get for being sleep deprived - I wrote this version looking at the release notes, rather than my own notes!
I did see a measurable effect with both standard and preview build systems though. It varies greatly between projects.

**Comment by fastred** [comment]
Thanks for contributing this!

**Pull request merged**
