### PR TITLE
Add forgotten `else`

### PR DESCRIPTION
**Pull request by dphov**
Add forgotten `else`  to Whole Module Optimization for CocoaPods code

### CODE REVIEW

**Comment by fastred** [comment]
I can't reproduce the need for this else statement. We don't touch `config.build_settings['SWIFT_OPTIMIZATION_LEVEL']` in configurations other than `Debug`, so the default should be used which is WMO.

**Comment by DenTelezhkin** [comment]
And by the way, this recommendation is going away completely in Xcode 10, since single-file compilation mode will be faster than this workaround.

https://developer.apple.com/videos/play/wwdc2018/408

**Comment by fabb** [comment]
No it‘s not. Our project still compiles 2-3x faster with wholemodule mode. But incremental compile times are better with the singlefile batch mode, so it depends on what we are working on, we might even temporarily switch it.

**Comment by DenTelezhkin** [comment]
Yeah, sorry for not mentioning it, of course i'm talking about incremental builds.

**Pull request closed without merging**
